#!/usr/bin/env python3
"""
board.py — generate STATE.md (the instrument panel) and WORK.md (what is in flight).

Both files are GENERATED. Every value is derived from a real artifact on disk or from
git; nothing is typed. That is the point: this repo has twice carried the same number in
two places and let them drift (FRAMEWORK said the golden was both 182 and 187).

    python3 scripts/board.py                 # regenerate both
    python3 scripts/board.py --check         # exit 1 if either is stale (for CI/tests)
    python3 scripts/board.py lanes           # what can safely run at the same time
    python3 scripts/board.py setup           # one-time per clone: hooks + merge driver
    python3 scripts/board.py capture         # push every worktree's uncommitted work
    python3 scripts/board.py new-tractate gittin

REFUSES TO OVERWRITE A HAND-EDIT. Each generated file embeds a checksum of its own body.
If the body on disk does not match, the file was edited by hand: board.py prints the diff
and exits non-zero rather than silently destroying the edit. `--force` overrides.

Every cell carries its dataset and its BLIND / CIRCULAR flag. A cell without provenance
is a bug in this generator, not a formatting choice (FRAMEWORK §3).

This script never runs a model, never runs evaluate_golden.py, and never writes anywhere
except STATE.md and WORK.md.
"""
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parent.parent
BANNER = "<!-- GENERATED by scripts/board.py — do not edit; run the script instead -->"
CKSUM = "<!-- board-checksum: {} -->"
LIVE_OPEN = "<!-- board-live:start -->"
LIVE_CLOSE = "<!-- board-live:end -->"

CAPS = ["triage", "detection", "classification", "boundaries", "review", "publication"]
CAP_TITLE = {
    "triage": "1 Triage", "detection": "2 Detection", "classification": "3 Classification",
    "boundaries": "4 Boundaries", "review": "5 Review", "publication": "6 Publication",
}
# Gates live in FRAMEWORK.md, which is the file that justifies them. Parsed, not retyped.
GATE_RE = re.compile(r"\*\*Gate: (.+?) — (PROVISIONAL|DERIVED)")
TRACTATES = ["ketubot", "kiddushin", "gittin", "yevamot", "eruvin"]


# ---------------------------------------------------------------- sources

def sh(*args: str) -> str:
    return subprocess.run(args, cwd=ROOT, capture_output=True, text=True).stdout.strip()


def load_json(rel: str):
    p = ROOT / rel
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def gates() -> dict[str, str]:
    """Read each capability's gate from FRAMEWORK.md rather than restating it."""
    txt = (ROOT / "FRAMEWORK.md").read_text()
    found = GATE_RE.findall(txt)
    out = {}
    for cap, (value, kind) in zip(CAPS, found):
        out[cap] = f"{value} · {kind}"
    for cap in CAPS:
        out.setdefault(cap, "not yet defined")
    return out


def goldens() -> dict[str, dict]:
    """Every golden on disk -- iterate TRACTATES, never a shorter hardcoded list.

    Until 2026-09-02 this looped over ("ketubot", "kiddushin") while TRACTATES held five.
    The Gittin golden landed and the coverage matrix printed the Classification cell as
    `⬜` -- "never measured" -- for a file sitting in results/canonical/. The board is the
    thing sessions read to decide what to work on, so an artifact it cannot see may as
    well not exist, and nothing raises: a missing golden and an unlooped tractate produce
    the same blank (Lesson 38 -- absence is quiet).

    `load_json` already returns nothing for a file that is not there, so the guard the
    short list was doing is the one the loop already does.
    """
    out = {}
    for t in TRACTATES:
        d = load_json(f"results/canonical/{t}_canonical.json")
        if not d:
            continue
        stories = [s for pg in d["pages"] for s in pg.get("stories", [])]
        # `accepted` = not NOT_A_STORY, which counts BORDERLINE as accepted. Gittin is
        # the first golden to carry that value and this figure does not distinguish it;
        # the split lives in the golden's own `classification_distribution`.
        accepted = [s for s in stories if s.get("classification") != "NOT_A_STORY"]
        out[t] = {"pages": len(d["pages"]), "entries": len(stories), "accepted": len(accepted)}
    return out


def rulers() -> dict[str, dict]:
    """Same fix, same reason: a ruler for a tractate not in the list was unreadable."""
    out = {}
    for t in TRACTATES:
        d = load_json(f"results/rulers/{t}_ruler.json")
        if d:
            out[t] = d.get("metrics", {})
    return out


def expert_lists() -> dict[str, dict]:
    """
    Expert ground truth on disk, each row sized in ITS OWN units.

    Two shapes live in this directory and they are not interchangeable:

    - a **story list** (`stories[]`), counted by its own `blind` / `counts_for_recall`
      flags and never by raw length (Lesson 29);
    - a **comment harvest** (`remarks[]`) — Jeff's anchored marginal remarks, sorted onto
      the axes. It has no `stories` key at all.

    Reading `d.get("stories", [])` for both printed
    `kiddushin_comments_harvested.json` as **0 parsed · 0 blind · 0 count for recall** in
    a table headed BLIND — i.e. as a ground-truth file holding nothing, when it holds 11
    sentence-level remarks including the 2005 margin note that retired an open question
    with Jeff without our having to spend one of his answers on it.

    Zero because the file is empty and zero because this function did not recognise the
    file are different facts and must print as different facts (Lesson 38). An unknown
    shape is named with its keys rather than sized at zero, so it reads as *unclassified*
    and not as *absent*.
    """
    out = {}
    p = ROOT / "results/expert_lists"
    if not p.exists():
        return out
    for f in sorted(p.glob("*.json")):
        d = load_json(str(f.relative_to(ROOT)))
        if not isinstance(d, dict):
            continue
        row = {"path": str(f.relative_to(ROOT))}
        if "stories" in d:
            # The same two filters `measure_recall_vs_expert_list.load_expert()` applies:
            # drop the duplicate first, THEN count the flags. Counting flags over the raw
            # list prints 91 where the harness's denominator is 90 — the board and the
            # harness must not disagree about the size of the same set.
            #
            # Found twice independently, which is worth recording. #6 found it by noticing
            # that this generated cell said 91 while STATUS.md, the ruler and
            # tests/test_kiddushin_list_parse.py all said 90 — `kiddushin_050` is one story
            # listed twice. #17 found it by re-deriving the denominator from the harness.
            # The generated file was the wrong one both times, which is the whole argument
            # for having exactly one of them. #6 applied the filter to `counts_for_recall`
            # alone; it belongs to `parsed` and `blind` too, so it is applied once, here.
            stories = [s for s in d["stories"] if s.get("duplicate_of") is None]
            row |= {
                "shape": "story_list",
                "parsed": len(stories),
                "blind": sum(1 for s in stories if s.get("blind")),
                "counts_for_recall": sum(
                    1 for s in stories if s.get("counts_for_recall", s.get("blind"))),
                "duplicates_dropped": len(d["stories"]) - len(stories),
            }
        elif "remarks" in d:
            row |= {
                "shape": "comment_harvest",
                "remarks": len(d["remarks"]),
                "comments": d.get("comments"),
            }
        else:
            row |= {"shape": "unrecognised", "keys": sorted(d)[:6]}
        out[f.stem] = row
    return out


def _expert_list_size(d: dict) -> str:
    """The size cell for one expert-list row, in the units that row actually has."""
    if d["shape"] == "story_list":
        dup = f" ({d['duplicates_dropped']} duplicate dropped)" if d.get("duplicates_dropped") else ""
        return (f"{d['parsed']} parsed{dup} · {d['blind']} blind "
                f"· {d['counts_for_recall']} count for recall")
    if d["shape"] == "comment_harvest":
        n = d["remarks"]
        src = f" from {d['comments']} comments" if d.get("comments") else ""
        return f"**{n} anchored remarks**{src} — not a story list, carries no recall denominator"
    return ("**shape not recognised by `board.py`** — top-level keys: "
            + ", ".join(f"`{k}`" for k in d["keys"]))


def items() -> list[dict]:
    out = []
    for d, done in ((ROOT / "work", False), (ROOT / "work/done", True)):
        if not d.exists():
            continue
        for f in sorted(d.glob("*.md")):
            if f.name in ("_TEMPLATE.md", "README.md"):
                continue
            m = re.match(r"^---\n(.*?)\n---\n", f.read_text(), re.S)
            if not m:
                continue
            fm = dict(re.findall(r"^(\w+):[ \t]*(.*)$", m.group(1), re.M))
            listy = lambda k: [x.strip() for x in fm.get(k, "").strip("[]").split(",") if x.strip()]
            out.append({
                "slug": f.stem, "done": done, "path": str(f.relative_to(ROOT)),
                "title": fm.get("title", f.stem),
                "capability": listy("capability"), "tractate": listy("tractate"),
                "blocked_by": listy("blocked_by"), "awaiting": listy("awaiting"),
                "writes": listy("writes"),
                "finding": fm.get("finding", "").strip(),
            })
    return out


# ------------------------------------------------- contention (not ordering)

def overlap(a: list[str], b: list[str]) -> list[str]:
    """Paths two items both write. A trailing `/` means the whole subtree.

    `blocked_by` is the ORDERING graph. This is the CONTENTION graph, and they are not
    the same: two items with no ordering relation between them are shown as concurrently
    runnable whether or not they write the same file. Six such pairs existed among the
    items runnable on 2026-08-31, four of them recommended together as the cheapest next
    steps.
    """
    hits = set()
    for x in a:
        for y in b:
            if x == y or x.startswith(y.rstrip("/") + "/") or y.startswith(x.rstrip("/") + "/"):
                hits.add(x if len(x) >= len(y) else y)
    return sorted(hits)


def collisions(its: list[dict]) -> list[tuple[str, str, list[str]]]:
    """Every pair of OPEN items that write a common path, with the paths."""
    import itertools
    open_items = [i for i in its if not i["done"]]
    out = []
    for a, b in itertools.combinations(sorted(open_items, key=lambda x: x["slug"]), 2):
        shared = overlap(a["writes"], b["writes"])
        if shared:
            out.append((a["slug"], b["slug"], shared))
    return out


def lanes(its: list[dict]) -> list[list[str]]:
    """Group open items so that two items in DIFFERENT lanes never write a common path.

    Connected components of the contention graph. A lane runs serially; lanes run in
    parallel. This is the number of concurrent sessions the work actually supports --
    which is not the number of unblocked items, and never has been.
    """
    open_items = sorted([i for i in its if not i["done"]], key=lambda x: x["slug"])
    parent = {i["slug"]: i["slug"] for i in open_items}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]; x = parent[x]
        return x

    for a, b, _ in collisions(its):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb
    groups: dict[str, list[str]] = {}
    for i in open_items:
        groups.setdefault(find(i["slug"]), []).append(i["slug"])
    return sorted(groups.values(), key=lambda g: (-len(g), g[0]))


def report_lanes() -> int:
    """Print the contention graph. Non-zero exit means at least one pair collides --
    which is information, not a failure: it says those two need one lane, not two."""
    its = items()
    cols = collisions(its)
    undeclared = [i["slug"] for i in its if not i["done"] and not i["writes"]]
    ls = lanes(its)

    print(f"{len([i for i in its if not i['done']])} open items -> "
          f"{len(ls)} lane(s) that can run concurrently\n")
    for n, g in enumerate(ls, 1):
        tag = "SERIAL" if len(g) > 1 else "alone "
        print(f"  lane {n:>2} [{tag}] {len(g)} item(s)")
        for s in g:
            print(f"              {s}")
    if cols:
        # Grouped by the contended path, not by pair: 39 pairs is unreadable and, more to
        # the point, six of them are one file. The path is the thing you act on.
        by_path: dict[str, set[str]] = {}
        for a, b, shared in cols:
            for p in shared:
                by_path.setdefault(p, set()).update((a, b))
        print(f"\n{len(cols)} colliding pair(s) over {len(by_path)} contended path(s):\n")
        for p, slugs in sorted(by_path.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            print(f"  {p}   <- {len(slugs)} items")
            for s in sorted(slugs):
                print(f"      {s}")
            print()
    if undeclared:
        print(f"{len(undeclared)} open item(s) declare no `writes:` -- their collisions "
              f"CANNOT be seen:\n  " + "\n  ".join(undeclared))
        return 1
    return 0


def worktrees() -> list[dict]:
    """In flight, from git — not from anyone remembering to update a status field."""
    out = []
    block: dict = {}
    for line in sh("git", "worktree", "list", "--porcelain").split("\n"):
        if line.startswith("worktree "):
            block = {"path": line.split(" ", 1)[1]}
        elif line.startswith("branch "):
            block["branch"] = line.split("/")[-1]
        elif line == "" and block:
            out.append(block); block = {}
    if block:
        out.append(block)
    for w in out:
        dirty = subprocess.run(["git", "status", "--porcelain"], cwd=w["path"],
                               capture_output=True, text=True).stdout.strip()
        # STATE.md and WORK.md are always about to change; counting them would make
        # this generator's own output depend on whether it had just run.
        w["uncommitted"] = len([x for x in dirty.split("\n")
                                if x.strip() and not x.endswith(("STATE.md", "WORK.md"))])
    return out


def jeff_questions() -> list[tuple[str, str]]:
    """Open questions, by slug, from comms/JEFF.md — the one place they live."""
    p = ROOT / "comms/JEFF.md"
    if not p.exists():
        return []
    txt = p.read_text()
    sec = re.search(r"## Open questions(.*?)(?=\n## |\Z)", txt, re.S)
    if not sec:
        return []
    return re.findall(r"^\|\s*`(jeff:[a-z0-9-]+)`\s*\|\s*([^|]+?)\s*\|", sec.group(1), re.M)


def recalls() -> dict:
    """Triage recall per tractate, read from the recall harness's own output.

    `results/<t>_jeff2005_matches.json` (no suffix) is ALWAYS the recall denominator —
    `--expert-filter recall` for a pre-parsed list, the whole document for Ketubot.
    Sensitivity variants carry a suffix and are deliberately not read here, so the cell
    cannot silently change which question it answers.

    This replaces a hardcoded `if t == "ketubot"`, which claimed Kiddushin triage was
    never measured for as long as the value lived only in prose.
    """
    out = {}
    for t in TRACTATES:
        f = ROOT / f"results/recall/{t}_jeff2005_matches.json"
        if not f.exists():
            continue
        rows = json.loads(f.read_text())
        if not rows or "survived_triage" not in rows[0]:
            continue   # pre-2026-08-31 artifact: no triage field, so no cell
        out[t] = {"n": len(rows),
                  "triage": sum(1 for r in rows if r["survived_triage"]) / len(rows),
                  # A story on pages that were all skipped cannot have been proposed,
                  # so `in_detector` implies `survived_triage` and the ratio is a true
                  # conditional. Verified 0 exceptions on both tractates, 2026-08-31.
                  "detection_given_triage": (
                      sum(1 for r in rows if r["in_detector"])
                      / max(sum(1 for r in rows if r["survived_triage"]), 1))}
    return out


# ---------------------------------------------------------------- rendering

def cell(v) -> str:
    return v if v else "⬜"


def render_state() -> str:
    g, r, el, gl, rc = gates(), rulers(), expert_lists(), goldens(), recalls()
    its = items()
    L = [BANNER, "", "# STATE — the instrument panel", "",
         "Generated by `scripts/board.py`. Every value below is read from an artifact on",
         "disk or from git; none is typed. The hand-written companion is",
         "[`STATUS.md`](STATUS.md) — the judgment, the hazards, the *\"treat this as",
         "indicated, not measured\"*. Neither replaces the other.", "",
         "**Every number names its dataset and says BLIND or CIRCULAR.** A cell without",
         "provenance is a bug in the generator (FRAMEWORK §3).", "",
         "## Coverage", "",
         "| | Triage | Detection | Classification | Boundaries | Review | Publication |",
         "|---|---|---|---|---|---|---|"]

    for t in TRACTATES:
        m = r.get(t, {})
        det = m.get("detection", {})
        detection = ""
        if t in rc:
            detection = f"{rc[t]['detection_given_triage']*100:.1f}% B"
        elif det:
            detection = f"{det['recall']*100:.1f}% / {det['recall_strict']*100:.1f}% B"
        # Classification and Boundaries have NO on-disk artifact carrying their
        # current value: they come from evaluate_golden.py and score_boundary_targets.py,
        # which write to a scratch path and are not run here. Typing them in would be the
        # exact drift this generator exists to stop, so the cell says where to look
        # instead of inventing a number. Making these derivable is a real gap, named in
        # the footnote below.
        classif = "STATUS · C" if t in gl else ""
        boundaries = "STATUS" if (ROOT / f"results/rulers/{t}_ruler.json").exists() else ""
        review = f"{len(rounds_for(t))} rounds" if rounds_for(t) else ""
        triage = f"{rc[t]['triage']*100:.1f}% · n={rc[t]['n']} B" if t in rc else ""
        L.append(f"| **{t.title()}** | {cell(triage)} | {cell(detection)} | {cell(classif)} "
                 f"| {cell(boundaries)} | {cell(review)} | ⬜ |")
    L += ["", "`B` = BLIND dataset (can measure recall) · `C` = CIRCULAR (precision only) · "
          "`⬜` = never measured.", "",
          "**Triage** is stories surviving, and **Detection** is recall *given the page",
          "survived triage* — both from `results/recall/*_jeff2005_matches.json`, whose",
          "denominator each cell states. Detection is conditioned because the two",
          "capabilities compose and have separate gates; charging Triage's losses to",
          "Detection as well double-counts them (Lesson 35).", "",
          "The **end-to-end** figure — what the pipeline delivers, `triage x detection` —",
          "is quoted **loose / strict** from `results/rulers/`, or from",
          "`results/recall/<t>_strict.json` for a tractate with no ruler yet:", ""]
    for t in TRACTATES:
        d = r.get(t, {}).get("detection", {})
        if d:
            L.append(f"- {t.title()}: **{d['recall']*100:.1f}% loose / "
                     f"{d['recall_strict']*100:.1f}% strict** on {d['denominator']} stories")
            continue
        # A tractate detected but not yet reviewed has no ruler — its strict figure
        # comes from measure_strict_recall.py, which applies the ruler's own
        # narrowing. Without this the matrix would show only the loose cell, and a
        # bare 100.0% is the exact shape the loose window's over-crediting takes.
        sr = load_json(f"results/recall/{t}_strict.json")
        if sr:
            L.append(f"- {t.title()}: **{sr['recall_loose']*100:.1f}% loose / "
                     f"{sr['recall_strict']*100:.1f}% strict** on {sr['denominator']} "
                     f"stories (no ruler yet — no expert round on this tractate)")
    L += ["",
          "The loose test credits a proposal anywhere in the aligner's window and is",
          "provably over-credited in at least one case, so read it as an upper bound.", "",
          "**Cells reading `STATUS` are a known gap in this generator, not a formatting**",
          "**choice.** Classification and Boundaries have no artifact on disk carrying",
          "their current value — they are produced by `evaluate_golden.py` and",
          "`score_boundary_targets.py`, which write to a scratch path this script does not",
          "read and must not re-run. (Triage left this list on 2026-08-31, when the recall",
          "harness started writing `survived_triage` per story, so the cell became",
          "derivable.) Until those scripts also write a small committed",
          "measurements file, the honest cell is a pointer to the hand-written number in",
          "[`STATUS.md`](STATUS.md), not a number typed into a generator that promises it",
          "types none.", ""]

    for cap in CAPS:
        L += [f"### {CAP_TITLE[cap]}", "```"]
        L.append(f"gate       {g[cap]}")
        hist = f"docs/capabilities/{CAPS.index(cap)+1}_{cap}.md"
        L.append(f"history    {hist}" if (ROOT / hist).exists() else "history    —")
        infl = [i for i in its if cap in i["capability"] and not i["done"]]
        if infl:
            for i in infl[:6]:
                flags = []
                if i["blocked_by"]:
                    flags.append("blocked: " + ", ".join(i["blocked_by"]))
                if i["awaiting"]:
                    flags.append("awaiting: " + ", ".join(i["awaiting"]))
                L.append(f"open       {i['slug']}" + (f"   ← {' · '.join(flags)}" if flags else ""))
        else:
            L.append("open       —")
        done = [i for i in its if cap in i["capability"] and i["done"]]
        L.append(f"closed     {len(done)} item(s) in work/done/")
        L += ["```", ""]

    L += ["## Ground truth on hand", "", "| dataset | kind | size |", "|---|---|---|"]
    for t, d in sorted(el.items()):
        kind = "**BLIND**" if d["shape"] != "unrecognised" else "**UNKNOWN**"
        L.append(f"| `{d['path']}` | {kind} | {_expert_list_size(d)} |")
    for t, d in sorted(gl.items()):
        L.append(f"| `results/canonical/{t}_canonical.json` | **CIRCULAR** | {d['pages']} pages "
                 f"· {d['entries']} entries · {d['accepted']} accepted |")
    for t, m in sorted(r.items()):
        det = m.get("detection", {})
        if det:
            L.append(f"| `results/rulers/{t}_ruler.json` | **JOINED** | denominator "
                     f"{det['denominator']} · found {det['found']} |")
    L += ["", "**Quote entries against entries and accepted against accepted, never one of "
          "each.** This project did exactly that for months.", ""]

    unfolded = unfolded_verdict_files()
    if unfolded:
        L += ["## Expert verdicts on disk that no ruler reads", "",
              "Each of these is a round Jeff gave us whose verdicts are not in any ruler, so",
              "they are invisible to every precision number. Lesson 1's failure, still live.",
              "Counts are measured; files holding zero verdicts are not listed, because",
              "naming an empty file as a lost round buries the one that is not.", ""]
        L += [f"- `validation/feedback/{f}` — **{n} verdicts**" for f, n in unfolded] + [""]

    q = jeff_questions()
    L += ["## Open with Jeff", ""]
    if q:
        L += ["| slug | question |", "|---|---|"] + [f"| `{s}` | {t} |" for s, t in q]
        waiting = [i for i in its if i["awaiting"]]
        if waiting:
            L += ["", "Items that can finish but cannot conclude until he answers:", ""]
            L += [f"- `{i['slug']}` — {', '.join(i['awaiting'])}" for i in waiting]
    else:
        L.append("`comms/JEFF.md` not present or has no open-questions table.")
    return "\n".join(L) + "\n"


def rounds_for(tractate: str) -> list[str]:
    """Review rounds actually folded into the ruler — the authoritative on-disk source.

    Counting verdict files in validation/feedback/ by filename does not work: most are
    named v5_1_feedback_* / canonical_review_* / v8_delta_* and carry no tractate in the
    name. The ruler records exactly which it consumed, so use that.
    """
    d = load_json(f"results/rulers/{tractate}_ruler.json") or {}
    return list((d.get("review_rounds") or {}).keys())


def _verdict_count(path) -> int:
    """
    How many expert verdicts a feedback file actually holds, across both shapes.

    The dict shape (`reviews`/`feedback` keyed "<ref>_<start>-<end>") is what every
    ruler reads. The list shape (`feedback` as a list of {ref, feedback_type, ...})
    is used by the 2026-01-08 round alone and is read by nothing.

    Counting matters because "unconsumed" is not "lost": of the three files this
    used to name, one holds 25 real verdicts, one has an EMPTY validations dict,
    and one is an automated eval trace with no expert judgement in it. Listing all
    three as lost expert work overstated the gap by two (measured 2026-08-31).
    """
    try:
        data = json.loads(path.read_text())
    except Exception:
        return 0
    if not isinstance(data, dict):
        return 0
    items = data.get("reviews") or data.get("feedback") or data.get("validations")
    if isinstance(items, dict):
        return sum(1 for v in items.values()
                   if isinstance(v, dict) and _is_verdict(v))
    if isinstance(items, list):
        return sum(1 for v in items if isinstance(v, dict) and _is_verdict(v))
    return 0


# The keys a round uses to carry the expert's judgement. A round is one of ours if it
# has ANY of them — the vocabularies differ per round and are mapped by
# `scripts/map_verdict_vocabularies.py`, not by this counter.
VERDICT_KEYS = ("verdict", "feedback_type", "is_story", "classification")


def _is_verdict(v: dict) -> bool:
    """
    An entry Jeff actually ruled on — counted by whether it carries a judgement FIELD,
    not by whether that field is truthy.

    Counting `v.get("feedback_type")` truthily dropped the 2026-01-08 round's **Ketubot
    17a** — `feedback_type: null` with a 300-character note in which he states the English
    and Aramaic do not correlate and then *quotes the Hebrew of the story the excerpt
    contains*. So the single richest verdict in the round was the one the inventory could
    not see, and this function's own docstring said "25 real verdicts" three lines above
    the code that printed 24.

    A null verdict with a note is not an absent verdict. It is an expert declining the
    dropdown and answering in prose, which is the most informative thing he does
    (Lesson 38: absence is quiet — an entry skipped without a count is indistinguishable
    from one that was never there).
    """
    return any(k in v for k in VERDICT_KEYS) or bool(v.get("notes"))


def unfolded_verdict_files() -> list[tuple[str, int]]:
    """
    Verdict files on disk that no ruler consumed, with how many verdicts each holds.

    Files holding zero are omitted: an empty file is not a silent gap, and naming it
    as one buries the file that IS.
    """
    used = set()
    for t in ("ketubot", "kiddushin"):
        used |= set(rounds_for(t))
    out = []
    for p in sorted((ROOT / "validation/feedback").glob("*.json")):
        if p.name in used or "Simon" in p.name:
            continue
        n = _verdict_count(p)
        if n:
            out.append((p.name, n))
    return out


def render_work() -> str:
    its, wts = items(), worktrees()
    open_items = [i for i in its if not i["done"]]
    L = [BANNER, "", "# WORK — what is open, and what is in flight right now", "",
         "Generated by `scripts/board.py`. `in flight` comes from `git worktree list`, not",
         "from anyone remembering to update a field — which is what would have shown that two",
         "of four branches on 2026-08-30 had never committed anything.", "",
         f"## Open — {len(open_items)} items", "",
         "| item | capability | tractate | blocked / awaiting |", "|---|---|---|---|"]
    for i in sorted(open_items, key=lambda x: x["slug"]):
        flags = []
        if i["blocked_by"]:
            flags.append("**blocked:** " + ", ".join(f"`{b}`" for b in i["blocked_by"]))
        if i["awaiting"]:
            flags.append("awaiting " + ", ".join(f"`{a}`" for a in i["awaiting"]))
        L.append(f"| [{i['title']}]({i['path']}) | {', '.join(i['capability']) or '—'} "
                 f"| {', '.join(i['tractate']) or '—'} | {' · '.join(flags) or '—'} |")

    L += ["", LIVE_OPEN, "## In flight", "",
          "*Live — read from git at generation time, and deliberately outside the",
          "staleness check: it changes whenever anyone edits anything.*", "",
          "| branch | worktree | uncommitted |", "|---|---|---|"]
    for w in wts:
        mark = f"**{w['uncommitted']} FILES**" if w.get("uncommitted") else "clean"
        L.append(f"| `{w.get('branch','(detached)')}` | `{w['path'].split('/')[-1]}` | {mark} |")

    L.append(LIVE_CLOSE)
    done = [i for i in its if i["done"]]
    L += ["", f"## Done — {len(done)} items, never deleted", "",
          "| item | capability | finding |", "|---|---|---|"]
    for i in sorted(done, key=lambda x: x["slug"]):
        fin = f"[{i['finding'].split('/')[-1]}]({i['finding']})" if i["finding"] else "—"
        L.append(f"| [{i['title']}]({i['path']}) | {', '.join(i['capability']) or '—'} | {fin} |")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- writing

def body_of(text: str) -> str:
    """The stable part: what the checksum covers and what --check compares.

    The live block is excluded on purpose. It reports the state of every worktree at
    generation time, so including it would make the file permanently 'stale' the moment
    anyone touched anything -- which would train people to ignore the check.
    """
    out, skip = [], False
    for l in text.split("\n"):
        if l.startswith(LIVE_OPEN):
            skip = True
        elif l.startswith(LIVE_CLOSE):
            skip = False
        elif not skip and not l.startswith("<!-- board-checksum:"):
            out.append(l)
    return "\n".join(out)


def stamp(text: str) -> str:
    h = hashlib.sha256(body_of(text).encode()).hexdigest()[:16]
    return text.rstrip("\n") + "\n" + CKSUM.format(h) + "\n"


def write(path: Path, text: str, force: bool, check: bool) -> bool:
    """Returns True if the file is already up to date. Refuses to clobber a hand-edit."""
    new = stamp(text)
    if path.exists():
        old = path.read_text()
        m = re.search(r"<!-- board-checksum: ([0-9a-f]+) -->", old)
        old_body = body_of(old)
        edited = not m or hashlib.sha256(old_body.encode()).hexdigest()[:16] != m.group(1)
        if edited and not force:
            print(f"REFUSING to overwrite {path.name}: it was edited by hand since the last "
                  f"generation.\nReconcile, then re-run with --force.\n")
            for line in list(difflib.unified_diff(
                    old_body.split("\n"), body_of(new).split("\n"),
                    fromfile=f"{path.name} (on disk)", tofile=f"{path.name} (generated)",
                    lineterm=""))[:60]:
                print(" ", line)
            sys.exit(2)
        if body_of(old) == body_of(new):
            return True
    if check:
        return False
    path.write_text(new)
    return False


def new_tractate(name: str) -> None:
    """Stamp out the standard campaign for a tractate, pre-linked and pre-ordered."""
    name = name.lower()
    seq = [("triage", ["triage"], []), ("detection", ["detection"], ["triage"]),
           ("classification", ["classification"], ["detection"]),
           ("review-ui", ["review"], ["classification"]),
           ("expert-round", ["review"], ["review-ui"]), ("golden", ["classification"], ["expert-round"])]
    made = []
    for stage, caps, deps in seq:
        slug = f"2026-08-30-{name}-{stage}"
        f = ROOT / "work" / f"{slug}.md"
        if f.exists():
            continue
        blocked = [f"2026-08-30-{name}-{d}" for d in deps]
        f.write_text(
            "---\n"
            f"title: {name.title()} — {stage.replace('-', ' ')}\n"
            f"capability: [{', '.join(caps)}]\n"
            f"tractate: [{name}]\n"
            f"blocked_by: [{', '.join(blocked)}]\n"
            "awaiting: []\nfinding:\nsuperseded_by:\n---\n\n"
            f"# {name.title()} — {stage.replace('-', ' ')}\n\n"
            "**Self-contained.** Read [`FRAMEWORK.md`](../FRAMEWORK.md) and\n"
            "[`docs/technical/new_tractate_workflow.md`](../docs/technical/new_tractate_workflow.md),\n"
            "which documents this sequence, then this.\n\n"
            "## Method\n\nSee the workflow doc; this item is the handle and the ordering.\n\n"
            "## Guardrails\n\n"
            "- **Ask Jeff to keep his appendix separate BEFORE the first review round**, not\n"
            "  after (Lesson 29). Once merged into his list it cannot be reconstructed, and the\n"
            "  list stops being able to measure what we missed.\n"
            "- Regenerate a same-day baseline before any comparison (Lesson 11).\n"
            "- Report the corrections ruler and the neutral ruler separately (Lesson 24).\n\n"
            "## When done\n\n"
            "Finding to `docs/findings/`, add `## Outcome`, `git mv` to `work/done/`.\n")
        made.append(slug)
    print(f"{len(made)} items created for {name}:" if made else f"nothing to create for {name}")
    for s in made:
        print("  work/" + s + ".md")



def reroot_links(text: str) -> str:
    """Rewrite links *out of* an item moving from `work/` into `work/done/`.

    Three shapes move, and all three used to break:

    - `](../x)`        -> `](../../x)`   — out of work/ entirely
    - `](sibling.md)`  -> `](../sibling.md)`  — a still-open item, one level up now
    - `](done/x.md)`   -> `](x.md)`      — an already-finished item, now a sibling

    Only the first was handled. An item that cited a sibling item — which is the normal
    way to say "the rest of this is that item's territory" — broke that link at the moment
    of finishing, and `finish`'s own docstring claimed links "run BOTH ways and both are
    handled". That is Lesson 31's shape again at one remove: the guard existed, the
    docstring overclaimed, and the case nobody had written yet was the one that broke.
    Caught by `test_bookkeeping.py::test_no_markdown_link_is_broken` on 2026-09-01, on the
    first item to link a sibling.

    Rewritten in ONE pass, deliberately. Written as three sequential `re.sub` calls, the
    `done/x.md` rule strips the prefix and the bare-sibling rule then re-adds `../` to the
    result — each rule correct alone, wrong in composition. Every link must be considered
    exactly once.

    **Not idempotent, and it cannot be.** `../x` and `done/x.md` are safe to re-run, but a
    bare sibling is not: once rewritten to `../sibling.md` it is indistinguishable from a
    link that legitimately points one level up, so a second pass would deepen it again.
    The predecessor was idempotent and this docstring said so; keeping the claim after
    adding a rule that breaks it is how a docstring starts lying. `finish` applies this
    exactly once, as the file moves — after which the source path no longer exists, so
    there is no second application to defend against. Do not call it from anywhere else.
    """
    def one(m: re.Match) -> str:
        target = m.group(1)
        if target.startswith("#") or "://" in target:
            # A same-page anchor, or an external URL. Neither is ours to move — and the
            # anchor only became reachable here once the pattern stopped excluding `#`,
            # so that it could keep re-rooting non-markdown paths.
            return m.group(0)
        if target.startswith("../"):
            # Out of work/ entirely — one level deeper now. `../../` is already correct.
            # NOT restricted to .md: items link `../results/...json` and `../scripts/...py`,
            # and narrowing this rule to markdown broke exactly those (caught by
            # test_every_open_item_would_survive_being_closed, 2026-09-01).
            return m.group(0) if target.startswith("../../") else f"](../{target})"
        if target.startswith("done/") and target.count("/") == 1:
            # An already-finished item: a sibling once we are inside work/done/.
            return f"]({target[len('done/'):]})"
        if "/" not in target and not target.startswith("."):
            # A still-open sibling in work/, now one level up.
            return f"](../{target})"
        return m.group(0)

    return re.sub(r"\]\(([^)\s]+)\)", one, text)


def reroot_inbound(text: str, linking_file: str, slug: str) -> str:
    """
    Rewrite links in `linking_file` that point at `work/<slug>.md` to `work/done/<slug>.md`.

    The inverse of `reroot_links`, which fixes links *out of* the moved item. This one
    fixes links *into* it — the direction `finish` used to ignore and the suite used to
    claim it handled. Finishing an item broke every reference to it: on 2026-08-31 two
    rows in `work/README.md`'s redirect table, twice in one session.

    `linking_file` is repo-relative and decides the shape of the fix: a link from
    `work/README.md` is a bare sibling (`<slug>.md`), one from the repo root is
    `work/<slug>.md`, one from `docs/findings/` is `../../work/<slug>.md`. Only the
    `work/` -> `work/done/` segment moves; whatever prefix got the linker there is
    preserved untouched.

    Idempotent: a path already containing `work/done/<slug>.md` is left alone, so a
    re-run cannot produce `done/done`.
    """
    linking_dir = PurePosixPath(linking_file).parent
    if linking_dir == PurePosixPath("work"):
        # Sibling reference from inside work/ — the link gains a `done/` segment.
        pattern = rf"\]\((?!done/)({re.escape(slug)}\.md)\)"
        return re.sub(pattern, r"](done/\1)", text)
    if linking_dir == PurePosixPath("work/done"):
        # An ALREADY-finished item referring to one that was still open: it wrote
        # `../<slug>.md`, which was right at the time. Once the target closes they are
        # siblings and the `../` is what breaks it.
        #
        # This case was missing, and it is the same defect as the one Lesson 31 records
        # -- a link broken at the exact moment an item becomes a permanent record --
        # surviving in the one direction nobody checked. It fired three times in one
        # session on 2026-09-02 before anyone read the error instead of editing the link
        # by hand, which is the tell: a fix you keep applying manually is a fix that
        # belongs in the tool.
        pattern = rf"\]\(\.\./(?!done/){re.escape(slug)}\.md\)"
        return re.sub(pattern, rf"]({slug}.md)", text)
    pattern = rf"\]\(((?:\.\./)*)work/(?!done/){re.escape(slug)}\.md\)"
    return re.sub(pattern, rf"](\1work/done/{slug}.md)", text)


def fix_inbound_links(slug: str) -> list[str]:
    """
    Repoint every reference to a just-finished item. Returns the files changed.

    Scans tracked *and* untracked-but-not-ignored markdown, because a reference written
    in the same session as the finish is exactly the one most likely to be stale, and it
    is not committed yet.
    """
    listings = (
        subprocess.run(["git", "ls-files", "*.md"], cwd=ROOT,
                       capture_output=True, text=True).stdout,
        subprocess.run(["git", "ls-files", "--others", "--exclude-standard", "*.md"],
                       cwd=ROOT, capture_output=True, text=True).stdout,
    )
    changed = []
    seen = set()
    for listing in listings:
        for rel in listing.split("\n"):
            if not rel or rel in seen or rel.startswith("archive/"):
                continue
            seen.add(rel)
            path = ROOT / rel
            # The moved item itself is handled by reroot_links, not here.
            if not path.exists() or rel == f"work/done/{slug}.md":
                continue
            before = path.read_text(errors="ignore")
            # Generated files are derived from the items themselves and are rewritten by
            # the next `board.py` run, so editing them here achieves nothing — and it
            # leaves them briefly disagreeing with what the generator would produce,
            # which `--check` correctly calls stale.
            if before.startswith(BANNER):
                continue
            after = reroot_inbound(before, rel, slug)
            if after != before:
                path.write_text(after)
                changed.append(rel)
    return changed


# Paths every item touches by construction, which therefore cannot indicate contention:
# the generated board (auto-resolved by the merge drivers), and the dated-slug files whose
# names cannot collide because nobody has to agree on them.
UNCONTENDED = ("STATE.md", "WORK.md", "docs/findings/", "lessons/", "work/")


def declared_vs_actual(slug: str) -> tuple[list[str], list[str]]:
    """What the item SAID it would write, against what the branch actually changed.

    `writes:` is filled in when an item is opened -- before the work is done, by whoever
    is opening it. Lesson 34 is precisely about such a field: a person who does not know
    a value leaves it blank, and an LLM session produces a confident, plausible, wrong
    one. A blank gets investigated; a confident wrong value does not.

    So the field has to be grounded against something. git is the only thing that knows
    what a branch really touched, and `finish` is the moment it knows it.

    Measured on the first item ever to carry the field: it under-declared 8 paths, one of
    which (tests/test_review_ui_symmetry.py) collides with `review-verdict-axes` -- an
    item the lane map printed as safe to run concurrently at that exact moment.
    """
    base = sh("git", "merge-base", "main", "HEAD")
    if not base:
        return [], []
    actual = [f for f in sh("git", "diff", "--name-only", f"{base}..HEAD").split("\n") if f]
    declared = next((i["writes"] for i in items() if i["slug"] == slug), [])
    missed = sorted(f for f in actual
                    if not f.startswith(UNCONTENDED)
                    and not any(overlap([f], [d]) for d in declared))
    unused = sorted(d for d in declared if not any(overlap([f], [d]) for f in actual))
    return missed, unused


def report_declaration_drift(slug: str) -> list[tuple[str, list[str]]]:
    """Print how the declaration diverged, and return the collisions it hid."""
    missed, unused = declared_vs_actual(slug)
    if not missed and not unused:
        return []
    if missed:
        print(f"\n  `writes:` under-declared {len(missed)} path(s) actually changed:")
        for m in missed:
            print(f"      + {m}")
    if unused:
        print(f"\n  declared but never touched (harmless -- costs a serialized lane):")
        for u in unused:
            print(f"      - {u}")
    hidden = []
    for i in items():
        if i["done"] or i["slug"] == slug:
            continue
        shared = overlap(missed, i["writes"])
        if shared:
            hidden.append((i["slug"], shared))
    return hidden


def finish(slug: str) -> None:
    """Close an item: rewrite its relative links, then git mv it into work/done/.

    Why this exists. Items live in work/ and link out with `../FRAMEWORK.md`. Finishing
    an item moves it one level deeper, so every one of those links breaks -- at the exact
    moment the item is supposed to become a permanent record. 60 links across 27 items
    were one `git mv` away from breaking when this was written, and the first item anyone
    actually finished broke one.

    Links run BOTH ways and both are handled: `reroot_links` fixes the links out of the
    item, `fix_inbound_links` repoints every reference to it. The second was missing
    until 2026-08-31 and broke a link every time an item was closed, while the test
    guarding this claimed "finishing cannot break them" — it only ever checked one
    direction (Lesson 31).

    Making the correct path the easy path beats remembering: `board.py finish <slug>`.
    """
    src = ROOT / "work" / f"{slug}.md"
    if not src.exists():
        print(f"no such item: work/{slug}.md"); sys.exit(1)
    text = src.read_text()
    if not re.search(r"^## Outcome$", text, re.M):
        print(f"work/{slug}.md has no `## Outcome` section.\n"
              f"Say what happened and WHY -- especially for a revert -- before closing it. "
              f"A revert we cannot explain gets re-tried.")
        sys.exit(1)
    fixed = reroot_links(text)
    src.write_text(fixed)
    dst = ROOT / "work" / "done" / f"{slug}.md"
    dst.parent.mkdir(parents=True, exist_ok=True)
    # git mv fails on a file git does not know about, which is the normal state of an
    # item created and closed in the same session. Fall back to a plain move rather than
    # a traceback; the result is identical and `git add` picks it up either way.
    if subprocess.run(["git", "mv", str(src), str(dst)], cwd=ROOT,
                      capture_output=True).returncode != 0:
        src.rename(dst)
        print("  (moved without git mv — the item was not tracked yet)")

    repointed = fix_inbound_links(slug)
    if repointed:
        print(f"  repointed {len(repointed)} inbound link(s): {', '.join(repointed)}")
    n = len(re.findall(r"\]\(\.\./(?!\.\./)", text))
    print(f"closed work/{slug}.md -> work/done/{slug}.md" + (f" ({n} links re-rooted)" if n else ""))

    # Ground the declaration against what the branch really did. This is the only moment
    # the truth is knowable, and an unchecked `writes:` is worse than none: it licenses
    # the confidence that two items are safe to run side by side.
    for other, shared in report_declaration_drift(slug):
        print(f"\n  !! an undeclared path collides with an OPEN item: {other}")
        print(f"     on: {', '.join(shared)}")
        print(f"     Anyone told those two were in different lanes was told wrong.")
        print(f"     Add these paths to `writes:` in work/done/{slug}.md before merging,")
        print(f"     so the next session's lane graph is right.")


def merge_driver(name: str, dest: str) -> int:
    """Resolve a conflict on a generated file by regenerating it.

    git hands a merge driver the two sides and wants the answer written to %A. For
    STATE.md and WORK.md the answer is never a blend of the two sides: it is whatever
    board.py produces from the merged inputs. So ignore both sides and regenerate.

    `%P` (the path being merged) would let one driver serve both files, but it needs git
    >= 2.44 and this repo has run on 2.43. The filename is passed explicitly instead.
    """
    write(ROOT / "STATE.md", render_state(), force=True, check=False)
    write(ROOT / "WORK.md", render_work(), force=True, check=False)
    Path(dest).write_text((ROOT / name).read_text())
    return 0


# Filenames that must never be swept into a WIP commit. Deliberately high-precision:
# a false positive here blocks a capture under time pressure, which is the one moment you
# cannot afford a tool arguing with you. Found by testing `capture` end to end -- a worktree
# branched before .gitignore gained `.env` had the secret committed AND PUSHED, and a
# pushed secret is in history forever. The ignored-file warning could not see it, because
# the whole problem is that it was not ignored.
SENSITIVE_NAMES = {"id_rsa", "id_ed25519", ".netrc", "credentials.json",
                   "service-account.json", ".npmrc", ".pypirc"}
SENSITIVE_SUFFIX = (".pem", ".key", ".p12", ".pfx", ".keystore")


def sensitive(paths: list[str]) -> list[str]:
    out = []
    for f in paths:
        base = Path(f).name
        if (base in SENSITIVE_NAMES or base == ".env" or base.startswith(".env.")
                or base.endswith(SENSITIVE_SUFFIX)):
            out.append(f)
    return sorted(out)


def capture(go: bool) -> int:
    """Commit and push every worktree's uncommitted work, on a branch of its own.

    THE ORDERING IS THE POINT. A commit is recoverable forever, even a broken one on a
    dead branch. An uncommitted working tree is one `git checkout` from gone -- and
    `git checkout` is step one of every merge you are about to do. So capture everything
    before integrating anything.

    This exists as a command rather than a documented procedure because this repo has
    already run the experiment. `git config core.hooksPath .githooks` was documented as a
    one-line fresh-clone step in 9be0586, and on 2026-08-31 a clone was found with it
    unset -- the guard CLAUDE.md called active was not active. A five-command procedure,
    to be run correctly in three worktrees, under time pressure, with unpushed work at
    stake, is not going to fare better than the one-command one did.

    Deliberately NOT tidy: no squashing, no fixing the failing test, no resolving
    anything. A messy commit that exists beats a clean one that does not.
    """
    wts = worktrees()
    print(f"{len(wts)} worktree(s).\n")
    todo, blocked = [], []
    for w in wts:
        path, branch = w["path"], w.get("branch", "(detached)")
        dirty = subprocess.run(["git", "status", "--porcelain", "--untracked-files=all"],
                               cwd=path, capture_output=True, text=True).stdout.strip()
        files = [l for l in dirty.split("\n") if l.strip()]
        # Ignored-but-present files are what `git add -A` silently leaves behind. They are
        # ignored on purpose most of the time and irreplaceable the rest of the time, so
        # they are reported and never committed.
        ign = [l for l in subprocess.run(
            ["git", "status", "--porcelain", "--ignored=matching", "--untracked-files=no"],
            cwd=path, capture_output=True, text=True).stdout.split("\n") if l.startswith("!!")]
        name = Path(path).name
        if not files:
            print(f"  clean    {name}  [{branch}]")
            continue
        # Re-running must be safe and additive. Someone WILL run this twice -- it is the
        # command you reach for when you are unsure whether you already ran it, and the
        # first version failed with "a branch named ... already exists", which under time
        # pressure reads as "capture is broken" rather than "capture already happened".
        cur = subprocess.run(["git", "branch", "--show-current"], cwd=path,
                             capture_output=True, text=True).stdout.strip()
        if cur.startswith("wip/"):
            wip = cur                       # already captured once; add to the same branch
        else:
            stem = f"wip/{name}-{sh('date', '+%m%d') or 'capture'}"
            wip, n = stem, 2
            while subprocess.run(["git", "rev-parse", "--verify", "-q", wip], cwd=path,
                                 capture_output=True).returncode == 0:
                wip, n = f"{stem}-{n}", n + 1
        print(f"  DIRTY    {name}  [{branch}]  {len(files)} file(s) -> {wip}")
        for l in files[:6]:
            print(f"               {l}")
        if len(files) > 6:
            print(f"               ... and {len(files) - 6} more")
        if ign:
            print(f"           !! {len(ign)} IGNORED file(s) present -- `git add -A` will NOT")
            print(f"              take these. Copy anything you need outside the repo first:")
            for l in ign[:4]:
                print(f"               {l}")
        secret = sensitive([l[3:].strip().strip('"') for l in files])
        if secret:
            print(f"           !! REFUSING: `git add -A` would commit and PUSH these:")
            for s in secret:
                print(f"               {s}")
            print(f"              A pushed secret is in history forever. Add them to")
            print(f"              .gitignore or move them out of the repo, then re-run.")
            blocked.append(name)
            continue
        todo.append((path, wip))

    if blocked:
        print(f"\n{len(blocked)} worktree(s) BLOCKED on a credential-shaped file: "
              f"{', '.join(blocked)}")
        print("Nothing was committed anywhere. Resolve those, then re-run.")
        return 1
    if not todo:
        print("\nNothing to capture.")
        return 0
    if not go:
        print(f"\nDRY RUN. {len(todo)} worktree(s) would be branched, committed and pushed.")
        print("Re-run with `board.py capture --go` to do it.")
        return 0

    stamp_ = sh("date", "+%F")
    for path, wip in todo:
        print(f"\ncapturing {Path(path).name} -> {wip}")
        cur = subprocess.run(["git", "branch", "--show-current"], cwd=path,
                             capture_output=True, text=True).stdout.strip()
        steps = ([] if cur == wip else [["git", "checkout", "-b", wip]])
        for args in (*steps,
                     ["git", "add", "-A"],
                     ["git", "commit", "-m", f"WIP capture: {Path(path).name}, "
                      f"uncommitted state at {stamp_}"],
                     ["git", "push", "-u", "origin", "HEAD"]):
            r = subprocess.run(args, cwd=path, capture_output=True, text=True)
            if r.returncode != 0:
                print(f"  FAILED: {' '.join(args)}\n  {r.stderr.strip()}")
                print("  STOPPING. Nothing after this point ran; nothing was lost.")
                return 1
            print(f"  ok  {' '.join(args[:3])}")
    print("\nAll captured and pushed. Now safe to merge, rebase and checkout.")
    return 0


def setup() -> int:
    """One-time per-clone wiring. Idempotent, so running it again is free.

    Two things need per-clone git config, and neither travels in a commit:

      core.hooksPath        the pre-commit guard on the immutable harness
      merge.board.driver    regenerate STATE.md / WORK.md instead of merging them

    They are done together deliberately. A fresh clone previously needed one remembered
    command and now needs one remembered command; adding a *second* setup step is how a
    setup step stops being run at all. On 2026-08-31 a clone was found with
    `core.hooksPath` unset -- the guard CLAUDE.md calls active was not active.
    """
    ok = True
    for k, v in (("core.hooksPath", ".githooks"),
                 ("merge.board-state.name", "regenerate STATE.md"),
                 ("merge.board-state.driver", "python3 scripts/board.py merge-driver STATE.md %A"),
                 ("merge.board-work.name", "regenerate WORK.md"),
                 ("merge.board-work.driver", "python3 scripts/board.py merge-driver WORK.md %A")):
        r = subprocess.run(["git", "config", k, v], cwd=ROOT, capture_output=True, text=True)
        if r.returncode != 0:
            print(f"  FAILED  git config {k}: {r.stderr.strip()}"); ok = False
        else:
            print(f"  set     {k} = {v}")
    print("\nboard merge driver and hooks path registered." if ok else "\nsetup incomplete.")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("command", nargs="?", default="generate")
    ap.add_argument("tractate", nargs="?", help="tractate name, item slug for `finish`, "
                                                "or generated filename for `merge-driver`")
    ap.add_argument("dest", nargs="?", help="merge-driver only: the path git wants written")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--go", action="store_true",
                    help="capture only: actually commit and push (default is a dry run)")
    a = ap.parse_args()

    if a.command == "finish":
        if not a.tractate:
            print("usage: board.py finish <item-slug>"); return 1
        finish(a.tractate)
        return 0

    if a.command == "new-tractate":
        if not a.tractate:
            print("usage: board.py new-tractate <name>"); return 1
        new_tractate(a.tractate)
        return 0

    if a.command == "lanes":
        try:
            return report_lanes()
        except BrokenPipeError:
            # `board.py lanes | head` is the obvious way to read this, and an unhandled
            # BrokenPipeError there looks like the command crashed.
            try:
                sys.stdout.close()
            finally:
                return 0

    if a.command == "setup":
        return setup()

    if a.command == "capture":
        return capture(go=a.go)

    if a.command == "merge-driver":
        if not a.tractate or not a.dest:
            print("usage: board.py merge-driver <STATE.md|WORK.md> <dest>"); return 1
        return merge_driver(a.tractate, a.dest)

    fresh = [write(ROOT / "STATE.md", render_state(), a.force, a.check),
             write(ROOT / "WORK.md", render_work(), a.force, a.check)]
    if a.check:
        if all(fresh):
            print("STATE.md and WORK.md are up to date")
            return 0
        print("STALE: run `python3 scripts/board.py` and commit the result")
        return 1
    print("wrote STATE.md and WORK.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
