#!/usr/bin/env python3
"""
board.py — generate STATE.md (the instrument panel) and WORK.md (what is in flight).

Both files are GENERATED. Every value is derived from a real artifact on disk or from
git; nothing is typed. That is the point: this repo has twice carried the same number in
two places and let them drift (FRAMEWORK said the golden was both 182 and 187).

    python3 scripts/board.py                 # regenerate both
    python3 scripts/board.py --check         # exit 1 if either is stale (for CI/tests)
    python3 scripts/board.py new-tractate gittin

REFUSES TO OVERWRITE A HAND-EDIT. Each generated file embeds a checksum of its own body.
If the body on disk does not match, the file was edited by hand: board.py prints the diff
and exits non-zero rather than silently destroying the edit. `--force` overrides.

Every cell carries its dataset and its BLIND / CIRCULAR flag. A cell without provenance
is a bug in this generator, not a formatting choice (FRAMEWORK §3).

This script never runs a model, never runs evaluate_golden.py, and never writes anywhere
except STATE.md and WORK.md.
"""
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANNER = "<!-- GENERATED by scripts/board.py — do not edit; run the script instead -->"
CKSUM = "<!-- board-checksum: {} -->"
LIVE_OPEN = "<!-- board-live:start -->"
LIVE_CLOSE = "<!-- board-live:end -->"

CAPS = ["triage", "detection", "classification", "boundaries", "review", "publication"]
CAP_TITLE = {
    "triage": "1 Triage", "detection": "2 Detection", "classification": "3 Classification",
    "boundaries": "4 Boundaries", "review": "5 Review", "publication": "6 Publication",
}
# Gates live in FRAMEWORK.md, which is the file that justifies them. Parsed, not retyped.
GATE_RE = re.compile(r"\*\*Gate: (.+?) — (PROVISIONAL|DERIVED)")
TRACTATES = ["ketubot", "kiddushin", "gittin", "yevamot", "eruvin"]


# ---------------------------------------------------------------- sources

def sh(*args: str) -> str:
    return subprocess.run(args, cwd=ROOT, capture_output=True, text=True).stdout.strip()


def load_json(rel: str):
    p = ROOT / rel
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def gates() -> dict[str, str]:
    """Read each capability's gate from FRAMEWORK.md rather than restating it."""
    txt = (ROOT / "FRAMEWORK.md").read_text()
    found = GATE_RE.findall(txt)
    out = {}
    for cap, (value, kind) in zip(CAPS, found):
        out[cap] = f"{value} · {kind}"
    for cap in CAPS:
        out.setdefault(cap, "not yet defined")
    return out


def goldens() -> dict[str, dict]:
    out = {}
    for t in ("ketubot", "kiddushin"):
        d = load_json(f"results/canonical/{t}_canonical.json")
        if not d:
            continue
        stories = [s for pg in d["pages"] for s in pg.get("stories", [])]
        accepted = [s for s in stories if s.get("classification") != "NOT_A_STORY"]
        out[t] = {"pages": len(d["pages"]), "entries": len(stories), "accepted": len(accepted)}
    return out


def rulers() -> dict[str, dict]:
    out = {}
    for t in ("ketubot", "kiddushin"):
        d = load_json(f"results/rulers/{t}_ruler.json")
        if d:
            out[t] = d.get("metrics", {})
    return out


def expert_lists() -> dict[str, dict]:
    """Blind story lists, counted by their own flags — never by raw length (Lesson 29)."""
    out = {}
    p = ROOT / "results/expert_lists"
    if not p.exists():
        return out
    for f in sorted(p.glob("*.json")):
        d = load_json(str(f.relative_to(ROOT)))
        if not isinstance(d, dict):
            continue
        stories = d.get("stories", [])
        out[f.stem.split("_")[0]] = {
            "parsed": len(stories),
            "blind": sum(1 for s in stories if s.get("blind")),
            "counts_for_recall": sum(1 for s in stories if s.get("counts_for_recall", s.get("blind"))),
            "path": str(f.relative_to(ROOT)),
        }
    return out


def items() -> list[dict]:
    out = []
    for d, done in ((ROOT / "work", False), (ROOT / "work/done", True)):
        if not d.exists():
            continue
        for f in sorted(d.glob("*.md")):
            if f.name in ("_TEMPLATE.md", "README.md"):
                continue
            m = re.match(r"^---\n(.*?)\n---\n", f.read_text(), re.S)
            if not m:
                continue
            fm = dict(re.findall(r"^(\w+):[ \t]*(.*)$", m.group(1), re.M))
            listy = lambda k: [x.strip() for x in fm.get(k, "").strip("[]").split(",") if x.strip()]
            out.append({
                "slug": f.stem, "done": done, "path": str(f.relative_to(ROOT)),
                "title": fm.get("title", f.stem),
                "capability": listy("capability"), "tractate": listy("tractate"),
                "blocked_by": listy("blocked_by"), "awaiting": listy("awaiting"),
                "finding": fm.get("finding", "").strip(),
            })
    return out


def worktrees() -> list[dict]:
    """In flight, from git — not from anyone remembering to update a status field."""
    out = []
    block: dict = {}
    for line in sh("git", "worktree", "list", "--porcelain").split("\n"):
        if line.startswith("worktree "):
            block = {"path": line.split(" ", 1)[1]}
        elif line.startswith("branch "):
            block["branch"] = line.split("/")[-1]
        elif line == "" and block:
            out.append(block); block = {}
    if block:
        out.append(block)
    for w in out:
        dirty = subprocess.run(["git", "status", "--porcelain"], cwd=w["path"],
                               capture_output=True, text=True).stdout.strip()
        # STATE.md and WORK.md are always about to change; counting them would make
        # this generator's own output depend on whether it had just run.
        w["uncommitted"] = len([x for x in dirty.split("\n")
                                if x.strip() and not x.endswith(("STATE.md", "WORK.md"))])
    return out


def jeff_questions() -> list[tuple[str, str]]:
    """Open questions, by slug, from comms/JEFF.md — the one place they live."""
    p = ROOT / "comms/JEFF.md"
    if not p.exists():
        return []
    txt = p.read_text()
    sec = re.search(r"## Open questions(.*?)(?=\n## |\Z)", txt, re.S)
    if not sec:
        return []
    return re.findall(r"^\|\s*`(jeff:[a-z0-9-]+)`\s*\|\s*([^|]+?)\s*\|", sec.group(1), re.M)


def recalls() -> dict:
    """Triage recall per tractate, read from the recall harness's own output.

    `results/<t>_jeff2005_matches.json` (no suffix) is ALWAYS the recall denominator —
    `--expert-filter recall` for a pre-parsed list, the whole document for Ketubot.
    Sensitivity variants carry a suffix and are deliberately not read here, so the cell
    cannot silently change which question it answers.

    This replaces a hardcoded `if t == "ketubot"`, which claimed Kiddushin triage was
    never measured for as long as the value lived only in prose.
    """
    out = {}
    for t in TRACTATES:
        f = ROOT / f"results/recall/{t}_jeff2005_matches.json"
        if not f.exists():
            continue
        rows = json.loads(f.read_text())
        if not rows or "survived_triage" not in rows[0]:
            continue   # pre-2026-08-31 artifact: no triage field, so no cell
        out[t] = {"n": len(rows),
                  "triage": sum(1 for r in rows if r["survived_triage"]) / len(rows),
                  # A story on pages that were all skipped cannot have been proposed,
                  # so `in_detector` implies `survived_triage` and the ratio is a true
                  # conditional. Verified 0 exceptions on both tractates, 2026-08-31.
                  "detection_given_triage": (
                      sum(1 for r in rows if r["in_detector"])
                      / max(sum(1 for r in rows if r["survived_triage"]), 1))}
    return out


# ---------------------------------------------------------------- rendering

def cell(v) -> str:
    return v if v else "⬜"


def render_state() -> str:
    g, r, el, gl, rc = gates(), rulers(), expert_lists(), goldens(), recalls()
    its = items()
    L = [BANNER, "", "# STATE — the instrument panel", "",
         "Generated by `scripts/board.py`. Every value below is read from an artifact on",
         "disk or from git; none is typed. The hand-written companion is",
         "[`STATUS.md`](STATUS.md) — the judgment, the hazards, the *\"treat this as",
         "indicated, not measured\"*. Neither replaces the other.", "",
         "**Every number names its dataset and says BLIND or CIRCULAR.** A cell without",
         "provenance is a bug in the generator (FRAMEWORK §3).", "",
         "## Coverage", "",
         "| | Triage | Detection | Classification | Boundaries | Review | Publication |",
         "|---|---|---|---|---|---|---|"]

    for t in TRACTATES:
        m = r.get(t, {})
        det = m.get("detection", {})
        detection = ""
        if t in rc:
            detection = f"{rc[t]['detection_given_triage']*100:.1f}% B"
        elif det:
            detection = f"{det['recall']*100:.1f}% / {det['recall_strict']*100:.1f}% B"
        # Classification and Boundaries have NO on-disk artifact carrying their
        # current value: they come from evaluate_golden.py and score_boundary_targets.py,
        # which write to a scratch path and are not run here. Typing them in would be the
        # exact drift this generator exists to stop, so the cell says where to look
        # instead of inventing a number. Making these derivable is a real gap, named in
        # the footnote below.
        classif = "STATUS · C" if t in gl else ""
        boundaries = "STATUS" if (ROOT / f"results/rulers/{t}_ruler.json").exists() else ""
        review = f"{len(rounds_for(t))} rounds" if rounds_for(t) else ""
        triage = f"{rc[t]['triage']*100:.1f}% · n={rc[t]['n']} B" if t in rc else ""
        L.append(f"| **{t.title()}** | {cell(triage)} | {cell(detection)} | {cell(classif)} "
                 f"| {cell(boundaries)} | {cell(review)} | ⬜ |")
    L += ["", "`B` = BLIND dataset (can measure recall) · `C` = CIRCULAR (precision only) · "
          "`⬜` = never measured.", "",
          "**Triage** is stories surviving, and **Detection** is recall *given the page",
          "survived triage* — both from `results/recall/*_jeff2005_matches.json`, whose",
          "denominator each cell states. Detection is conditioned because the two",
          "capabilities compose and have separate gates; charging Triage's losses to",
          "Detection as well double-counts them (Lesson 35).", "",
          "The **end-to-end** figure — what the pipeline delivers, `triage x detection` —",
          "is quoted **loose / strict** from `results/rulers/`:", ""]
    for t in TRACTATES:
        d = r.get(t, {}).get("detection", {})
        if d:
            L.append(f"- {t.title()}: **{d['recall']*100:.1f}% loose / "
                     f"{d['recall_strict']*100:.1f}% strict** on {d['denominator']} stories")
    L += ["",
          "The loose test credits a proposal anywhere in the aligner's window and is",
          "provably over-credited in at least one case, so read it as an upper bound.", "",
          "**Cells reading `STATUS` are a known gap in this generator, not a formatting**",
          "**choice.** Classification and Boundaries have no artifact on disk carrying",
          "their current value — they are produced by `evaluate_golden.py` and",
          "`score_boundary_targets.py`, which write to a scratch path this script does not",
          "read and must not re-run. (Triage left this list on 2026-08-31, when the recall",
          "harness started writing `survived_triage` per story, so the cell became",
          "derivable.) Until those scripts also write a small committed",
          "measurements file, the honest cell is a pointer to the hand-written number in",
          "[`STATUS.md`](STATUS.md), not a number typed into a generator that promises it",
          "types none.", ""]

    for cap in CAPS:
        L += [f"### {CAP_TITLE[cap]}", "```"]
        L.append(f"gate       {g[cap]}")
        hist = f"docs/capabilities/{CAPS.index(cap)+1}_{cap}.md"
        L.append(f"history    {hist}" if (ROOT / hist).exists() else "history    —")
        infl = [i for i in its if cap in i["capability"] and not i["done"]]
        if infl:
            for i in infl[:6]:
                flags = []
                if i["blocked_by"]:
                    flags.append("blocked: " + ", ".join(i["blocked_by"]))
                if i["awaiting"]:
                    flags.append("awaiting: " + ", ".join(i["awaiting"]))
                L.append(f"open       {i['slug']}" + (f"   ← {' · '.join(flags)}" if flags else ""))
        else:
            L.append("open       —")
        done = [i for i in its if cap in i["capability"] and i["done"]]
        L.append(f"closed     {len(done)} item(s) in work/done/")
        L += ["```", ""]

    L += ["## Ground truth on hand", "", "| dataset | kind | size |", "|---|---|---|"]
    for t, d in sorted(el.items()):
        L.append(f"| `{d['path']}` | **BLIND** | {d['parsed']} parsed · {d['blind']} blind "
                 f"· {d['counts_for_recall']} count for recall |")
    for t, d in sorted(gl.items()):
        L.append(f"| `results/canonical/{t}_canonical.json` | **CIRCULAR** | {d['pages']} pages "
                 f"· {d['entries']} entries · {d['accepted']} accepted |")
    for t, m in sorted(r.items()):
        det = m.get("detection", {})
        if det:
            L.append(f"| `results/rulers/{t}_ruler.json` | **JOINED** | denominator "
                     f"{det['denominator']} · found {det['found']} |")
    L += ["", "**Quote entries against entries and accepted against accepted, never one of "
          "each.** This project did exactly that for months.", ""]

    unfolded = unfolded_verdict_files()
    if unfolded:
        L += ["## Expert verdicts on disk that no ruler reads", "",
              "Each of these is a round Jeff gave us whose verdicts are not in any ruler, so",
              "they are invisible to every precision number. Lesson 1's failure, still live.", ""]
        L += [f"- `validation/feedback/{f}`" for f in unfolded] + [""]

    q = jeff_questions()
    L += ["## Open with Jeff", ""]
    if q:
        L += ["| slug | question |", "|---|---|"] + [f"| `{s}` | {t} |" for s, t in q]
        waiting = [i for i in its if i["awaiting"]]
        if waiting:
            L += ["", "Items that can finish but cannot conclude until he answers:", ""]
            L += [f"- `{i['slug']}` — {', '.join(i['awaiting'])}" for i in waiting]
    else:
        L.append("`comms/JEFF.md` not present or has no open-questions table.")
    return "\n".join(L) + "\n"


def rounds_for(tractate: str) -> list[str]:
    """Review rounds actually folded into the ruler — the authoritative on-disk source.

    Counting verdict files in validation/feedback/ by filename does not work: most are
    named v5_1_feedback_* / canonical_review_* / v8_delta_* and carry no tractate in the
    name. The ruler records exactly which it consumed, so use that.
    """
    d = load_json(f"results/rulers/{tractate}_ruler.json") or {}
    return list((d.get("review_rounds") or {}).keys())


def unfolded_verdict_files() -> list[str]:
    """Verdict files on disk that no ruler consumed. A silent gap worth surfacing."""
    used = set()
    for t in ("ketubot", "kiddushin"):
        used |= set(rounds_for(t))
    out = []
    for p in sorted((ROOT / "validation/feedback").glob("*.json")):
        if p.name not in used and "Simon" not in p.name:
            out.append(p.name)
    return out


def render_work() -> str:
    its, wts = items(), worktrees()
    open_items = [i for i in its if not i["done"]]
    L = [BANNER, "", "# WORK — what is open, and what is in flight right now", "",
         "Generated by `scripts/board.py`. `in flight` comes from `git worktree list`, not",
         "from anyone remembering to update a field — which is what would have shown that two",
         "of four branches on 2026-08-30 had never committed anything.", "",
         f"## Open — {len(open_items)} items", "",
         "| item | capability | tractate | blocked / awaiting |", "|---|---|---|---|"]
    for i in sorted(open_items, key=lambda x: x["slug"]):
        flags = []
        if i["blocked_by"]:
            flags.append("**blocked:** " + ", ".join(f"`{b}`" for b in i["blocked_by"]))
        if i["awaiting"]:
            flags.append("awaiting " + ", ".join(f"`{a}`" for a in i["awaiting"]))
        L.append(f"| [{i['title']}]({i['path']}) | {', '.join(i['capability']) or '—'} "
                 f"| {', '.join(i['tractate']) or '—'} | {' · '.join(flags) or '—'} |")

    L += ["", LIVE_OPEN, "## In flight", "",
          "*Live — read from git at generation time, and deliberately outside the",
          "staleness check: it changes whenever anyone edits anything.*", "",
          "| branch | worktree | uncommitted |", "|---|---|---|"]
    for w in wts:
        mark = f"**{w['uncommitted']} FILES**" if w.get("uncommitted") else "clean"
        L.append(f"| `{w.get('branch','(detached)')}` | `{w['path'].split('/')[-1]}` | {mark} |")

    L.append(LIVE_CLOSE)
    done = [i for i in its if i["done"]]
    L += ["", f"## Done — {len(done)} items, never deleted", "",
          "| item | capability | finding |", "|---|---|---|"]
    for i in sorted(done, key=lambda x: x["slug"]):
        fin = f"[{i['finding'].split('/')[-1]}]({i['finding']})" if i["finding"] else "—"
        L.append(f"| [{i['title']}]({i['path']}) | {', '.join(i['capability']) or '—'} | {fin} |")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- writing

def body_of(text: str) -> str:
    """The stable part: what the checksum covers and what --check compares.

    The live block is excluded on purpose. It reports the state of every worktree at
    generation time, so including it would make the file permanently 'stale' the moment
    anyone touched anything -- which would train people to ignore the check.
    """
    out, skip = [], False
    for l in text.split("\n"):
        if l.startswith(LIVE_OPEN):
            skip = True
        elif l.startswith(LIVE_CLOSE):
            skip = False
        elif not skip and not l.startswith("<!-- board-checksum:"):
            out.append(l)
    return "\n".join(out)


def stamp(text: str) -> str:
    h = hashlib.sha256(body_of(text).encode()).hexdigest()[:16]
    return text.rstrip("\n") + "\n" + CKSUM.format(h) + "\n"


def write(path: Path, text: str, force: bool, check: bool) -> bool:
    """Returns True if the file is already up to date. Refuses to clobber a hand-edit."""
    new = stamp(text)
    if path.exists():
        old = path.read_text()
        m = re.search(r"<!-- board-checksum: ([0-9a-f]+) -->", old)
        old_body = body_of(old)
        edited = not m or hashlib.sha256(old_body.encode()).hexdigest()[:16] != m.group(1)
        if edited and not force:
            print(f"REFUSING to overwrite {path.name}: it was edited by hand since the last "
                  f"generation.\nReconcile, then re-run with --force.\n")
            for line in list(difflib.unified_diff(
                    old_body.split("\n"), body_of(new).split("\n"),
                    fromfile=f"{path.name} (on disk)", tofile=f"{path.name} (generated)",
                    lineterm=""))[:60]:
                print(" ", line)
            sys.exit(2)
        if body_of(old) == body_of(new):
            return True
    if check:
        return False
    path.write_text(new)
    return False


def new_tractate(name: str) -> None:
    """Stamp out the standard campaign for a tractate, pre-linked and pre-ordered."""
    name = name.lower()
    seq = [("triage", ["triage"], []), ("detection", ["detection"], ["triage"]),
           ("classification", ["classification"], ["detection"]),
           ("review-ui", ["review"], ["classification"]),
           ("expert-round", ["review"], ["review-ui"]), ("golden", ["classification"], ["expert-round"])]
    made = []
    for stage, caps, deps in seq:
        slug = f"2026-08-30-{name}-{stage}"
        f = ROOT / "work" / f"{slug}.md"
        if f.exists():
            continue
        blocked = [f"2026-08-30-{name}-{d}" for d in deps]
        f.write_text(
            "---\n"
            f"title: {name.title()} — {stage.replace('-', ' ')}\n"
            f"capability: [{', '.join(caps)}]\n"
            f"tractate: [{name}]\n"
            f"blocked_by: [{', '.join(blocked)}]\n"
            "awaiting: []\nfinding:\nsuperseded_by:\n---\n\n"
            f"# {name.title()} — {stage.replace('-', ' ')}\n\n"
            "**Self-contained.** Read [`FRAMEWORK.md`](../FRAMEWORK.md) and\n"
            "[`docs/technical/new_tractate_workflow.md`](../docs/technical/new_tractate_workflow.md),\n"
            "which documents this sequence, then this.\n\n"
            "## Method\n\nSee the workflow doc; this item is the handle and the ordering.\n\n"
            "## Guardrails\n\n"
            "- **Ask Jeff to keep his appendix separate BEFORE the first review round**, not\n"
            "  after (Lesson 29). Once merged into his list it cannot be reconstructed, and the\n"
            "  list stops being able to measure what we missed.\n"
            "- Regenerate a same-day baseline before any comparison (Lesson 11).\n"
            "- Report the corrections ruler and the neutral ruler separately (Lesson 24).\n\n"
            "## When done\n\n"
            "Finding to `docs/findings/`, add `## Outcome`, `git mv` to `work/done/`.\n")
        made.append(slug)
    print(f"{len(made)} items created for {name}:" if made else f"nothing to create for {name}")
    for s in made:
        print("  work/" + s + ".md")



def reroot_links(text: str) -> str:
    """Rewrite `](../x)` to `](../../x)` for a file moving one directory deeper.

    Already-deeper links (`../../`) are left alone, so running this twice is safe.
    """
    return re.sub(r"\]\((\.\./)(?!\.\./)", r"](../../", text)


def finish(slug: str) -> None:
    """Close an item: rewrite its relative links, then git mv it into work/done/.

    Why this exists. Items live in work/ and link out with `../FRAMEWORK.md`. Finishing
    an item moves it one level deeper, so every one of those links breaks -- at the exact
    moment the item is supposed to become a permanent record. 60 links across 27 items
    were one `git mv` away from breaking when this was written, and the first item anyone
    actually finished broke one.

    Making the correct path the easy path beats remembering: `board.py finish <slug>`.
    """
    src = ROOT / "work" / f"{slug}.md"
    if not src.exists():
        print(f"no such item: work/{slug}.md"); sys.exit(1)
    text = src.read_text()
    if not re.search(r"^## Outcome$", text, re.M):
        print(f"work/{slug}.md has no `## Outcome` section.\n"
              f"Say what happened and WHY -- especially for a revert -- before closing it. "
              f"A revert we cannot explain gets re-tried.")
        sys.exit(1)
    fixed = reroot_links(text)
    src.write_text(fixed)
    dst = ROOT / "work" / "done" / f"{slug}.md"
    dst.parent.mkdir(parents=True, exist_ok=True)
    # git mv fails on a file git does not know about, which is the normal state of an
    # item created and closed in the same session. Fall back to a plain move rather than
    # a traceback; the result is identical and `git add` picks it up either way.
    if subprocess.run(["git", "mv", str(src), str(dst)], cwd=ROOT,
                      capture_output=True).returncode != 0:
        src.rename(dst)
        print("  (moved without git mv — the item was not tracked yet)")
    n = len(re.findall(r"\]\(\.\./(?!\.\./)", text))
    print(f"closed work/{slug}.md -> work/done/{slug}.md" + (f" ({n} links re-rooted)" if n else ""))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("command", nargs="?", default="generate")
    ap.add_argument("tractate", nargs="?", help="tractate name, or item slug for `finish`")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    if a.command == "finish":
        if not a.tractate:
            print("usage: board.py finish <item-slug>"); return 1
        finish(a.tractate)
        return 0

    if a.command == "new-tractate":
        if not a.tractate:
            print("usage: board.py new-tractate <name>"); return 1
        new_tractate(a.tractate)
        return 0

    fresh = [write(ROOT / "STATE.md", render_state(), a.force, a.check),
             write(ROOT / "WORK.md", render_work(), a.force, a.check)]
    if a.check:
        if all(fresh):
            print("STATE.md and WORK.md are up to date")
            return 0
        print("STALE: run `python3 scripts/board.py` and commit the result")
        return 1
    print("wrote STATE.md and WORK.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
