#!/usr/bin/env python3
"""Compare v9 regex text spans vs v10 LLM text spans per story.

Writes a markdown report categorizing each real story by how its
text_span_* fields changed. Useful for Jeff's Wave 4 review and as the
Phase 4 ship-gate artifact.

Usage:
  python scripts/diff_v9_v10_spans.py [--tractate kiddushin|ketubot]
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parent.parent
V9_DIR = ROOT / 'results' / 'v9' / 'wave3'
V10_DIR = ROOT / 'results' / 'v10' / 'wave4'
OUT_DIR = ROOT / 'docs' / 'golden' / 'v10'

FILE_PAIRS = {
    'kiddushin': [('kiddushin_v9.json', 'kiddushin_v10.json')],
    'ketubot': [
        ('ketubot_v9_2-60.json', 'ketubot_v10_2-60.json'),
        ('ketubot_v9_61-112.json', 'ketubot_v10_61-112.json'),
    ],
}


def _span_offset(span: Optional[Dict]) -> Optional[int]:
    if not span:
        return None
    return span.get('char_offset')


def _categorize(v9_start, v9_end, v10_start, v10_end) -> str:
    v9_has = bool(v9_start) or bool(v9_end)
    v10_has = bool(v10_start) or bool(v10_end)
    if not v9_has and not v10_has:
        return 'both_full'
    if v9_has and not v10_has:
        return 'recovered_text'  # v9 trimmed, v10 keeps full
    if not v9_has and v10_has:
        return 'new_trim'  # v10 cuts something v9 didn't
    # Both have spans — compare offsets
    if _span_offset(v9_start) == _span_offset(v10_start) \
            and _span_offset(v9_end) == _span_offset(v10_end):
        return 'identical_trim'
    return 'different_trim'


def _story_key(page_ref: str, story: Dict) -> str:
    s = story.get('start_segment')
    e = story.get('end_segment')
    return f"{page_ref}_{s}-{e}"


def _index(pages: List[Dict]) -> Dict[str, Dict]:
    out = {}
    for page in pages:
        ref = page.get('ref', '')
        for s in page.get('stories', []):
            if s.get('classification') == 'NOT_A_STORY':
                continue
            out[_story_key(ref, s)] = s
    return out


def _short_heb(seg_hebrew: str, max_len: int = 80) -> str:
    s = (seg_hebrew or '').strip()
    if len(s) <= max_len:
        return s
    return s[:max_len] + '…'


def _format_span(span: Optional[Dict], full_text: str) -> str:
    if not span:
        return '—'
    off = span.get('char_offset')
    src = span.get('source', '?')
    head = _short_heb(full_text[:off]) if off else ''
    tail = _short_heb(full_text[off:]) if off is not None else ''
    return f"@{off} ({src})  «{head}» │ «{tail}»"


def compare(tractate: str) -> Tuple[Counter, List[Dict]]:
    pairs = FILE_PAIRS[tractate]
    counts = Counter()
    details = []
    for v9_name, v10_name in pairs:
        with (V9_DIR / v9_name).open() as f:
            v9 = json.load(f)
        with (V10_DIR / v10_name).open() as f:
            v10 = json.load(f)
        v9_idx = _index(v9['pages'])
        v10_idx = _index(v10['pages'])
        # Segments by (ref, idx) for text rendering
        seg_text: Dict[Tuple[str, int], str] = {}
        for page in v9['pages']:
            ref = page.get('ref', '')
            for s in page.get('segments', []):
                seg_text[(ref, s.get('index'))] = s.get('hebrew', '') or ''

        for key, v9s in v9_idx.items():
            v10s = v10_idx.get(key)
            if v10s is None:
                continue
            v9_ts, v9_te = v9s.get('text_span_start'), v9s.get('text_span_end')
            v10_ts, v10_te = v10s.get('text_span_start'), v10s.get('text_span_end')
            cat = _categorize(v9_ts, v9_te, v10_ts, v10_te)
            counts[cat] += 1
            ref, idx = key.rsplit('_', 1)
            s_idx_str = idx.split('-')[0]
            start_seg_idx = int(s_idx_str)
            end_seg_idx = int(idx.split('-')[1])
            start_text = seg_text.get((ref, start_seg_idx), '')
            end_text = seg_text.get((ref, end_seg_idx), '')
            details.append({
                'key': key,
                'category': cat,
                'classification': v9s.get('classification'),
                'v9_start': _format_span(v9_ts, start_text),
                'v9_end': _format_span(v9_te, end_text),
                'v10_start': _format_span(v10_ts, start_text),
                'v10_end': _format_span(v10_te, end_text),
                'v10_source': v10s.get('text_span_source'),
            })
    return counts, details


def write_report(tractate: str, counts: Counter, details: List[Dict]):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / f'wave4_diff_{tractate}.md'

    lines = [
        f"# Wave 4 v9-vs-v10 span diff — {tractate.title()}",
        '',
        'Generated by `scripts/diff_v9_v10_spans.py`.',
        '',
        'Categories:',
        '- `identical_trim` — v9 regex and v10 LLM agree.',
        '- `recovered_text` — v9 trimmed, v10 keeps full text.',
        '- `new_trim` — v10 trims something v9 missed.',
        '- `different_trim` — both trim, but at different offsets.',
        '- `both_full` — neither side emitted a trim.',
        '',
        '## Summary',
        '',
    ]
    total = sum(counts.values())
    for cat in ['identical_trim', 'recovered_text', 'new_trim',
                'different_trim', 'both_full']:
        n = counts.get(cat, 0)
        pct = (n / total * 100) if total else 0
        lines.append(f"- **{cat}**: {n} ({pct:.1f}%)")
    lines.append('')
    lines.append(f"Total real stories compared: {total}")
    lines.append('')

    for cat in ['recovered_text', 'new_trim', 'different_trim',
                'identical_trim', 'both_full']:
        rows = [d for d in details if d['category'] == cat]
        if not rows:
            continue
        lines.append(f"## {cat} ({len(rows)} stories)")
        lines.append('')
        for d in rows:
            lines.append(f"### `{d['key']}` ({d['classification']})")
            lines.append(f"- v10 source: `{d['v10_source']}`")
            lines.append(f"- v9  start: {d['v9_start']}")
            lines.append(f"- v10 start: {d['v10_start']}")
            lines.append(f"- v9  end:   {d['v9_end']}")
            lines.append(f"- v10 end:   {d['v10_end']}")
            lines.append('')
    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"  → {out_path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--tractate', choices=['kiddushin', 'ketubot', 'both'],
                        default='both')
    args = parser.parse_args()

    targets = ['kiddushin', 'ketubot'] if args.tractate == 'both' \
        else [args.tractate]
    for t in targets:
        print(f"\n=== {t.title()} ===")
        counts, details = compare(t)
        total = sum(counts.values())
        for cat, n in counts.most_common():
            pct = (n / total * 100) if total else 0
            print(f"  {cat:18s} {n:4d}  ({pct:5.1f}%)")
        print(f"  total real stories: {total}")
        write_report(t, counts, details)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
